# Homebrew formula for lw.
#
# Two formulas exist for this project, and they are not the same file:
#
#   * The tap's copy — github.com/awepo-pro/homebrew-tap's Formula/lw.rb — is
#     GENERATED by goreleaser's `brews` section (.goreleaser.yaml) when the
#     maintainer runs `goreleaser release`. It installs the release tarball's
#     prebuilt binary, with the tag's version and the tarball's sha256 stamped
#     in. That is the copy `brew install awepo-pro/tap/lw` gets.
#
#   * This in-tree copy builds from source instead. It needs no sha256 because
#     it clones at the tag, so it works the moment the tag is pushed, before
#     any tap exists:
#
#       brew install --build-from-source ./Formula/lw.rb
#
#     Bump `tag`/`version` together when the release tag moves.
class Lw < Formula
  desc "Compiles immutable sources into a reviewable markdown wiki; the agent gets no filesystem verbs"
  homepage "https://github.com/awepo-pro/lw"
  url "https://github.com/awepo-pro/lw.git",
      tag: "v0.1.0"
  version "0.1.0"
  license "MIT"

  depends_on "go" => :build

  def install
    # One static binary — the same constraint .goreleaser.yaml enforces. A
    # formula that shipped a cgo-linked build would not run over SSH on a
    # machine with nothing but a shell, which is the deployment lw targets.
    ENV["CGO_ENABLED"] = "0"
    system "go", "build", *std_go_args(ldflags: "-s -w -X main.version=v#{version}"), "./cmd/lw"
  end

  test do
    # `lw --version` prints "lw <version>"; the stamp is the only thing a
    # formula can assert without a vault, and it proves the ldflags landed.
    assert_match "lw v#{version}", shell_output("#{bin}/lw --version")
  end
end
